// Auto-generated by Vortex Engine — the scripting API your behaviours build on (IntelliSense stub;
// the engine provides the real implementation at runtime). Edit your own scripts, not this file.
namespace Vortex
{
    public struct Vector3
    {
        public float X, Y, Z;
        public Vector3(float x, float y, float z) { X = x; Y = y; Z = z; }
        public static Vector3 Zero => new Vector3(0f, 0f, 0f);
        public static Vector3 One => new Vector3(1f, 1f, 1f);
        public static Vector3 Up => new Vector3(0f, 1f, 0f);
        public static Vector3 Forward => new Vector3(0f, 0f, 1f);
    }

    /// <summary>Base class for all gameplay behaviours (like MonoBehaviour).</summary>
    public abstract class VortexBehaviour
    {
        /// <summary>Engine id of the entity this behaviour is attached to.</summary>
        public long EntityId { get; internal set; }

        /// <summary>World position of this entity (read/write).</summary>
        public Vector3 Position { get; set; }
        /// <summary>Euler rotation in degrees (X = pitch, Y = yaw, Z = roll).</summary>
        public Vector3 Rotation { get; set; }
        /// <summary>Unit forward vector in world space, from this entity's yaw + pitch.</summary>
        public Vector3 Forward => Vector3.Forward;
        /// <summary>Unit right vector (horizontal) in world space, from this entity's yaw.</summary>
        public Vector3 Right => new Vector3(1f, 0f, 0f);

        /// <summary>Move this entity by a delta.</summary>
        public void Translate(float dx, float dy, float dz) { }
        /// <summary>Rotate this entity by a delta (degrees).</summary>
        public void Rotate(float dPitch, float dYaw, float dRoll) { }

        public virtual void Start() { }
        public virtual void Update(float dt) { }
        public virtual void OnDestroy() { }
    }

    /// <summary>Keyboard + mouse input. Key names match WPF keys, e.g. "W", "Space", "Left".</summary>
    public static class Input
    {
        public static bool GetKey(string key) => false;
        /// <summary>Mouse movement since the last tick, in pixels (non-zero only while the game has the cursor).</summary>
        public static float MouseDeltaX { get; }
        public static float MouseDeltaY { get; }

        // Controller / gamepad (first connected pad). Sticks/triggers are -1..1 / 0..1 with dead zones.
        public static bool GamepadConnected => false;
        public static float LeftStickX => 0f;
        public static float LeftStickY => 0f;
        public static float RightStickX => 0f;
        public static float RightStickY => 0f;
        public static float LeftTrigger => 0f;
        public static float RightTrigger => 0f;
        /// <summary>Button held? Names: A B X Y LB RB Back Start LeftStick RightStick DPadUp/Down/Left/Right.</summary>
        public static bool GetGamepadButton(string name) => false;
        /// <summary>Button pressed this tick (edge)?</summary>
        public static bool GetGamepadButtonDown(string name) => false;
    }

    /// <summary>Frame timing.</summary>
    public static class Time
    {
        public static float DeltaTime => 0f;
    }

    /// <summary>RGBA color, channels 0..1.</summary>
    public struct Color
    {
        public float R, G, B, A;
        public Color(float r, float g, float b, float a) { R = r; G = g; B = b; A = a; }
        public static Color Rgb(int r, int g, int b) => new Color(r / 255f, g / 255f, b / 255f, 1f);
        public static Color Rgba(int r, int g, int b, int a) => new Color(r / 255f, g / 255f, b / 255f, a / 255f);
    }

    /// <summary>Scene control — the GAME decides when/which scene to load (e.g. lobby PLAY -> "Match").</summary>
    public static class Scene { public static void Load(string name) { } }

    /// <summary>Mouse mode. Locked = captured + hidden for mouse-look; unlocked = free cursor for UI.</summary>
    public static class Cursor { public static bool Locked { get; set; } }

    /// <summary>Application-level control.</summary>
    public static class Application { public static void Quit() { } }

    /// <summary>Player camera control.</summary>
    public static class Camera { public static void SetFieldOfView(float fovDegrees) { } }

    /// <summary>Collision. MoveCharacter resolves a character capsule (feet, radius, height) against the scene's
    /// colliders (solid ground/walls/props, no clipping). Grounded = resting on a surface. characterId (e.g. your
    /// EntityId) stops other characters walking through you.</summary>
    public static class Physics
    {
        public static bool Grounded => false;
        public static Vector3 MoveCharacter(Vector3 feet, float radius, float height, Vector3 move) => new Vector3(feet.X + move.X, feet.Y + move.Y, feet.Z + move.Z);
        public static Vector3 MoveCharacter(Vector3 feet, float radius, float height, Vector3 move, long characterId) => new Vector3(feet.X + move.X, feet.Y + move.Y, feet.Z + move.Z);
    }

    /// <summary>Generic engine settings (the GAME's options menu applies these).</summary>
    public static class Settings
    {
        public static void SetVSync(bool on) { }
        public static void ToggleFullscreen() { }
        public static bool IsFullscreen => false;
    }

    /// <summary>Lighting / atmosphere — flicker, lightning, mood. A static scene keeps what you last set.</summary>
    public static class Lighting
    {
        public static void SetAmbient(float strength) { }
        public static void SetDirectional(float dx, float dy, float dz, float r, float g, float b, float intensity) { }
        public static void ClearLights() { }
    }

    /// <summary>Script-built world geometry — assemble a level/backdrop from meshes (render-only).</summary>
    public static class World
    {
        public static void Add(string meshPath, float x, float y, float z, float yawDegrees, float scale) { }
        public static void Clear() { }
    }

    /// <summary>Immediate-mode 2D overlay (drawn each frame over the 3D). align: 0/1/2 = left/center/right.</summary>
    public static class UI
    {
        public static float Width => 0f;
        public static float Height => 0f;
        public static float MouseX => 0f;
        public static float MouseY => 0f;
        public static bool MouseDown => false;
        public static void Rect(float x, float y, float w, float h, Color c, float radius) { }
        public static void Rect(float x, float y, float w, float h, Color c) { }
        public static void Text(string text, float x, float y, float w, float h, float size, Color c, int align, int weight) { }
        public static void Text(string text, float x, float y, float w, float h, float size, Color c) { }
        public static void Line(float x1, float y1, float x2, float y2, Color c, float thick) { }
        public static void Image(string path, float x, float y, float w, float h, Color tint) { }
        public static void Image(string path, float x, float y, float w, float h) { }
        public static bool Hover(float x, float y, float w, float h) => false;
        public static bool Button(float x, float y, float w, float h, string label, Color bg, Color fg, float size, float radius) => false;
    }

    /// <summary>A loaded retained-UI screen (.vui). Drive named slots + read events by stable id.</summary>
    public sealed class VuiHandle
    {
        public bool IsValid => false;
        public void Show() { }
        public void Hide() { }
        public void SetValue(string id, float v) { }
        public void SetText(string id, string t) { }
        public void SetVisible(string id, bool v) { }
        public void SetColor(string id, Color c) { }
        public void SetImage(string id, string asset) { }
        public void SetList(string id, System.Collections.Generic.IReadOnlyList<System.Collections.Generic.IReadOnlyDictionary<string, string>> rows) { }
        public bool WasClicked(string id) => false;
        public float GetSlider(string id) => 0f;
        public bool GetToggle(string id) => false;
        public string GetText(string id) => "";
        public int GetStep(string id) => 0;
        public int GetCapturedKey(string id) => 0;
    }

    /// <summary>Retained-mode 2D UI: load .vui screens, stack them, drive them by id.</summary>
    public static class Gui
    {
        public static VuiHandle Load(string name) => new VuiHandle();
        public static VuiHandle Push(string name) => new VuiHandle();
        public static void Pop() { }
        public static bool HasScreens => false;
    }
}
